"""
transcript_parser.py — Multi-format transcript parser.

Supported: .vtt, .srt, .txt, .docx, .pdf, .csv, .json, .md
"""
from __future__ import annotations

import csv
import io
import json as json_mod
import logging
import re
import unicodedata
from pathlib import Path
from typing import Optional

from .config import TRANSCRIPT_MAX_WORDS, TRANSCRIPT_MIN_CHARS
from .models import ParsedTranscript, TranscriptMetadata, Turn

logger = logging.getLogger(__name__)

# Type alias for raw parsed turns: (speaker, text, start_time_sec)
RawTurn = tuple[str, str, Optional[float]]

# Boilerplate patterns to strip
_BOILERPLATE_RE = re.compile(
    r"(Transcribed by Otter\.ai|DISCLAIMER:|This transcript was produced|"
    r"Auto-generated by|Powered by Rev\.com|www\.[a-z]+\.com)",
    re.IGNORECASE,
)

_HTML_TAG_RE = re.compile(r"<[^>]+>")
_VOICE_TAG_RE = re.compile(r"<v ([^>]+)>")  # <v Speaker Name>
_TIMESTAMP_INLINE_RE = re.compile(r"\b\d{1,2}:\d{2}(:\d{2})?(\.\d+)?\b")
_HEADER_LINE_RE = re.compile(
    r"^(Meeting(\s*(#|Type|Name|Title))?|Leader|Role|Participants|Date|Location|Duration|Agenda|Subject|Topic|Project"
    r"|Customer|Call\s*Title|Time(\s*/\s*Time\s*Zone)?|Time\s*Zone|Company|Attendees|Facilitator"
    r"|Prepared\s*by|Recorded\s*by|Type|Title|Reference|Notes|Duration)\s*:",
    re.IGNORECASE,
)

# VTT header / special block markers
_VTT_BLOCK_SKIP_RE = re.compile(r"^(STYLE|NOTE|REGION)\b", re.IGNORECASE)

# SRT index lines (digit-only lines)
_SRT_INDEX_RE = re.compile(r"^\d+$")
# SRT bracketed speaker: "[Speaker Name] text"
_SRT_BRACKET_SPEAKER_RE = re.compile(r"^\[([^\]]{1,60})\]\s*(.*)")
# SRT/VTT timecode
_TIMECODE_RE = re.compile(
    r"\d{2}:\d{2}:\d{2}[.,]\d{3}\s*-->\s*\d{2}:\d{2}:\d{2}[.,]\d{3}"
)


# ── Exceptions ────────────────────────────────────────────────────────────────

class TranscriptParseError(ValueError):
    pass


# ── Utilities ─────────────────────────────────────────────────────────────────

def _normalize_text(text: str) -> str:
    """Strip BOM, normalize line endings, normalize unicode."""
    text = text.lstrip("\ufeff")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    # Normalize unicode to NFC
    text = unicodedata.normalize("NFC", text)
    return text


def _strip_html(text: str) -> str:
    return _HTML_TAG_RE.sub("", text).strip()


def _clean_speaker(label: str) -> str:
    """Trim and title-case speaker label."""
    return label.strip()


# Abbreviated titles that legitimately end with a period
_TITLE_ABBREV_RE = re.compile(
    r"\b(Mr|Mrs|Ms|Dr|Jr|Sr|St|Prof|Rev|Gen|Gov|Rep|Sen|Sgt|Cpl|Capt|Col|Lt|Cmdr)\.$",
    re.IGNORECASE,
)
# Common lowercase words allowed in names (particles / prefixes)
_NAME_PARTICLES = frozenset({
    "de", "del", "della", "van", "von", "der", "den", "al", "el", "la", "le", "di", "du", "da",
})


def _is_plausible_speaker(label: str) -> bool:
    """Reject labels that look like sentence fragments rather than names.

    Speaker labels are typically 1–4 words (occasionally 5 with titles),
    contain no sentence punctuation, and are mostly capitalised.
    """
    words = label.split()
    if not words:
        return False
    # Too many words for a person's name / role label
    if len(words) > 5:
        return False
    # Sentence-ending punctuation (periods not after known title abbreviations)
    if "." in label and not _TITLE_ABBREV_RE.search(label):
        return False
    # Commas indicate sentence fragments, not names
    if "," in label:
        return False
    # If multiple words, the majority should be capitalised (proper noun)
    if len(words) > 1:
        non_cap = sum(
            1 for w in words
            if w[0].islower() and w.lower() not in _NAME_PARTICLES
        )
        if non_cap > len(words) // 2:
            return False
    return True


def _dedupe_speakers(speakers: list[str]) -> list[str]:
    """Case-insensitive deduplicate preserving first-seen casing."""
    seen: dict[str, str] = {}
    for s in speakers:
        key = s.lower()
        if key not in seen:
            seen[key] = s
    return list(seen.values())


def _parse_timecode(tc: str) -> float:
    """Convert a timecode string (HH:MM:SS.mmm or HH:MM:SS,mmm) to seconds."""
    tc = tc.strip().replace(",", ".")
    parts = tc.split(":")
    if len(parts) == 3:
        return int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])
    if len(parts) == 2:
        return int(parts[0]) * 60 + float(parts[1])
    return float(parts[0])


def _normalize_speaker_map(turns: list[RawTurn]) -> list[RawTurn]:
    """
    Normalise speaker labels across all turns (case-insensitive dedup).
    Returns turns with unified speaker labels.
    """
    canon: dict[str, str] = {}
    for speaker, _, _ts in turns:
        key = speaker.lower()
        if key not in canon:
            canon[key] = speaker
    return [(canon[speaker.lower()], text, ts) for speaker, text, ts in turns]


def _merge_consecutive(turns: list[RawTurn]) -> list[RawTurn]:
    """Merge consecutive turns from the same speaker, keeping earliest timestamp."""
    if not turns:
        return []
    merged: list[RawTurn] = [turns[0]]
    for speaker, text, ts in turns[1:]:
        if speaker.lower() == merged[-1][0].lower():
            merged[-1] = (merged[-1][0], merged[-1][1] + " " + text, merged[-1][2])
        else:
            merged.append((speaker, text, ts))
    return merged


def _to_turn_objects(raw: list[RawTurn]) -> list[Turn]:
    return [
        Turn(turn_id=i + 1, speaker_label=speaker, text=text.strip(),
             start_time_sec=ts)
        for i, (speaker, text, ts) in enumerate(raw)
        if text.strip()
    ]


def _word_count(turns: list[Turn]) -> int:
    return sum(len(t.text.split()) for t in turns)


def _truncate_at_word_boundary(turns: list[Turn], max_words: int) -> list[Turn]:
    """Truncate turns so cumulative word count stays within max_words.

    Whole turns are dropped once the budget is exceeded, but the first turn
    is always included (its text is trimmed to max_words if necessary) so
    that truncation never returns an empty list.
    """
    if not turns:
        return []

    result: list[Turn] = []
    total = 0
    for turn in turns:
        words = turn.text.split()
        wc = len(words)
        if total + wc > max_words:
            if not result:
                # First turn exceeds budget — trim its text to fit.
                trimmed_text = " ".join(words[:max_words])
                result.append(Turn(
                    turn_id=turn.turn_id,
                    speaker_label=turn.speaker_label,
                    text=trimmed_text,
                    speaker_role_hint=turn.speaker_role_hint,
                ))
                total = max_words
            break
        result.append(turn)
        total += wc
    return result


# ── VTT Parser ────────────────────────────────────────────────────────────────

_TIMECODE_START_RE = re.compile(r"(\d{2}:\d{2}:\d{2}[.,]\d{3})\s*-->")


def _parse_vtt(text: str) -> list[Turn]:
    """
    Parse WebVTT content.
    Handles: voice tags <v Speaker>, "Speaker: text", no-attribution.
    """
    lines = text.splitlines()
    raw_turns: list[RawTurn] = []

    # Skip WEBVTT header line
    start = 0
    for i, line in enumerate(lines):
        if line.strip().upper() == "WEBVTT":
            start = i + 1
            break

    i = start
    while i < len(lines):
        line = lines[i].strip()

        # Skip STYLE / NOTE / REGION blocks
        if _VTT_BLOCK_SKIP_RE.match(line):
            while i < len(lines) and lines[i].strip():
                i += 1
            i += 1
            continue

        # Timecode line
        if _TIMECODE_RE.search(line):
            # Extract start time from the timecode
            tc_match = _TIMECODE_START_RE.search(line)
            cue_start: Optional[float] = None
            if tc_match:
                cue_start = _parse_timecode(tc_match.group(1))
            i += 1
            # Collect cue payload lines
            payload_lines: list[str] = []
            while i < len(lines) and lines[i].strip():
                payload_lines.append(lines[i])
                i += 1
            if payload_lines:
                _process_vtt_cue(payload_lines, raw_turns, cue_start)
            continue

        i += 1

    raw_turns = _normalize_speaker_map(raw_turns)
    raw_turns = _merge_consecutive(raw_turns)
    return _to_turn_objects(raw_turns)


def _process_vtt_cue(
    payload_lines: list[str],
    raw_turns: list[RawTurn],
    cue_start: Optional[float] = None,
) -> None:
    for line in payload_lines:
        # Style A: <v Speaker Name>text
        voice_match = _VOICE_TAG_RE.match(line)
        if voice_match:
            speaker = _clean_speaker(voice_match.group(1))
            text = _strip_html(line[voice_match.end():])
            if text:
                raw_turns.append((speaker, text, cue_start))
            continue

        # Strip remaining HTML tags
        clean = _strip_html(line)
        if not clean:
            continue

        # Style B: "Speaker: text"
        if ": " in clean:
            parts = clean.split(": ", 1)
            speaker = _clean_speaker(parts[0])
            text = parts[1].strip()
            if speaker and text:
                raw_turns.append((speaker, text, cue_start))
                continue

        # Style C: no attribution
        raw_turns.append(("Unknown", clean, cue_start))


# ── SRT Parser ────────────────────────────────────────────────────────────────

def _parse_srt(text: str) -> list[Turn]:
    """Parse SRT subtitle format."""
    lines = text.splitlines()
    raw_turns: list[RawTurn] = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        # Index line
        if _SRT_INDEX_RE.match(line):
            i += 1
            # Timecode
            cue_start: Optional[float] = None
            if i < len(lines) and _TIMECODE_RE.search(lines[i]):
                tc_match = _TIMECODE_START_RE.search(lines[i])
                if tc_match:
                    cue_start = _parse_timecode(tc_match.group(1))
                i += 1
            payload_lines = []
            while i < len(lines) and lines[i].strip():
                payload_lines.append(lines[i].strip())
                i += 1
            for pl in payload_lines:
                clean = _strip_html(pl)
                if not clean:
                    continue
                # Bracketed speaker: [Speaker Name] text
                bracket_m = _SRT_BRACKET_SPEAKER_RE.match(clean)
                if bracket_m:
                    speaker = _clean_speaker(bracket_m.group(1))
                    text = bracket_m.group(2).strip()
                    if speaker and text:
                        raw_turns.append((speaker, text, cue_start))
                        continue
                if ": " in clean:
                    parts = clean.split(": ", 1)
                    raw_turns.append((_clean_speaker(parts[0]), parts[1].strip(), cue_start))
                else:
                    raw_turns.append(("Unknown", clean, cue_start))
            continue
        i += 1

    raw_turns = _normalize_speaker_map(raw_turns)
    raw_turns = _merge_consecutive(raw_turns)
    return _to_turn_objects(raw_turns)


# ── TXT Parser ────────────────────────────────────────────────────────────────

def _match_rate(lines: list[str], pattern: re.Pattern) -> float:
    """Fraction of non-empty lines that match pattern."""
    non_empty = [l for l in lines if l.strip()]
    if not non_empty:
        return 0.0
    return sum(1 for l in non_empty if pattern.search(l)) / len(non_empty)


# Sub-format patterns
_FMT_A_RE = re.compile(r"^([A-Za-z][^:]{0,60}):\s+\S")  # "Speaker: text"
_FMT_B_SPEAKER_TS_RE = re.compile(r"^([A-Za-z][^:]{0,60})\s+(\d{1,2}:\d{2}(?::\d{2})?)\s*$")  # "Speaker HH:MM" or "Speaker HH:MM:SS"
_FMT_C_RE = re.compile(                                    # "[HH:MM:SS] speaker: text"
    r"^\[\d{1,2}:\d{2}(?::\d{2})?\]\s*([^:]{1,60}):\s*(.*)"
)
_FMT_E_RE = re.compile(r"^([A-Za-z][^:]{0,60})\s*\(\d{1,2}:\d{2}")  # "Speaker (HH:MM):"
# Separator / decoration lines to skip
_SEPARATOR_RE = re.compile(r"^[=\-_*]{3,}$")


def _fmt_a_line_count(lines: list[str]) -> int:
    """Count non-header lines that match Format A with a plausible speaker."""
    count = 0
    for l in lines:
        l = l.strip()
        if not l:
            continue
        m = _FMT_A_RE.match(l)
        if m and not _HEADER_LINE_RE.match(l) and _is_plausible_speaker(m.group(1).strip()):
            count += 1
    return count


def _parse_txt(text: str) -> list[Turn]:
    lines = text.splitlines()

    # Try Format C: "[HH:MM:SS] speaker: text" (bracketed timestamp prefix)
    # Check this early since it's unambiguous and won't false-positive.
    if _match_rate(lines, _FMT_C_RE) > 0.3:
        return _parse_txt_format_c(lines)

    # Try Format A: "Speaker: text"
    # Use both match rate and absolute count — long multi-line turns
    # dilute the rate even though the format is clearly "Speaker: text".
    fmt_a_rate = _match_rate(lines, _FMT_A_RE)
    fmt_a_count = _fmt_a_line_count(lines)
    if fmt_a_rate > 0.5 or (fmt_a_count >= 4 and fmt_a_rate > 0.05):
        return _parse_txt_format_a(lines)

    # Try Format E: "Speaker (timestamp):\ntext"
    if _match_rate(lines, _FMT_E_RE) > 0.3:
        return _parse_txt_format_e(lines)

    # Try Format B: "Speaker  timestamp\ntext"
    if _match_rate(lines, _FMT_B_SPEAKER_TS_RE) > 0.3:
        return _parse_txt_format_b(lines)

    # Try Format D: "Speaker\ntext" separated by blank lines
    turns_d = _parse_txt_format_d(lines)
    if len(turns_d) > 1:
        return turns_d

    # Fallback: single turn
    full = " ".join(l for l in lines if l.strip())
    return [Turn(turn_id=1, speaker_label="Unknown", text=full, start_time_sec=None)]


_FMT_C_TS_RE = re.compile(r"^\[(\d{1,2}:\d{2}(?::\d{2})?)\]")


def _parse_txt_format_c(lines: list[str]) -> list[Turn]:
    """'[HH:MM:SS] speaker: text' — bracketed timestamp prefix per line."""
    raw: list[RawTurn] = []
    for line in lines:
        line = line.strip()
        if not line or _BOILERPLATE_RE.search(line):
            continue
        if _SEPARATOR_RE.match(line):
            continue
        m = _FMT_C_RE.match(line)
        if m:
            speaker = _clean_speaker(m.group(1))
            text = m.group(2).strip()
            ts: Optional[float] = None
            ts_m = _FMT_C_TS_RE.match(line)
            if ts_m:
                try:
                    ts = _parse_timecode(ts_m.group(1))
                except (ValueError, IndexError):
                    pass
            if speaker and text:
                raw.append((speaker, text, ts))
        # Skip non-matching lines (headers, separators, etc.)
    raw = _normalize_speaker_map(raw)
    raw = _merge_consecutive(raw)
    return _to_turn_objects(raw)


def _parse_txt_format_a(lines: list[str]) -> list[Turn]:
    raw: list[RawTurn] = []
    current_speaker: Optional[str] = None
    current_text: list[str] = []

    for line in lines:
        line = line.strip()
        if not line or _BOILERPLATE_RE.search(line):
            continue
        m = _FMT_A_RE.match(line)
        if m and not _HEADER_LINE_RE.match(line) and _is_plausible_speaker(m.group(1).strip()):
            if current_speaker and current_text:
                raw.append((current_speaker, " ".join(current_text), None))
            current_speaker = _clean_speaker(m.group(1))
            colon_pos = line.index(":", len(m.group(1)) - 1)
            rest = line[colon_pos + 1:].strip()
            current_text = [rest] if rest else []
        else:
            if current_speaker:
                current_text.append(line)
            # else drop orphaned lines

    if current_speaker and current_text:
        raw.append((current_speaker, " ".join(current_text), None))

    raw = _normalize_speaker_map(raw)
    raw = _merge_consecutive(raw)
    return _to_turn_objects(raw)


_FMT_B_TS_RE = re.compile(r"\s+(\d{1,2}:\d{2}(?::\d{2})?)\s*$")


def _parse_txt_format_b(lines: list[str]) -> list[Turn]:
    """Otter.ai: 'Speaker  HH:MM\ntext' blocks."""
    raw: list[RawTurn] = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if _BOILERPLATE_RE.search(line):
            i += 1
            continue
        m = _FMT_B_SPEAKER_TS_RE.match(line)
        if m and not _HEADER_LINE_RE.match(line):
            speaker = _clean_speaker(m.group(1))
            ts: Optional[float] = None
            ts_m = _FMT_B_TS_RE.search(line)
            if ts_m:
                try:
                    ts = _parse_timecode(ts_m.group(1))
                except (ValueError, IndexError):
                    pass
            i += 1
            text_lines = []
            while i < len(lines) and lines[i].strip() and not _FMT_B_SPEAKER_TS_RE.match(lines[i]):
                text_lines.append(lines[i].strip())
                i += 1
            if text_lines:
                raw.append((speaker, " ".join(text_lines), ts))
        else:
            i += 1
    raw = _normalize_speaker_map(raw)
    raw = _merge_consecutive(raw)
    return _to_turn_objects(raw)


def _parse_txt_format_d(lines: list[str]) -> list[Turn]:
    """'Speaker\ntext\n\n' blocks separated by blank lines."""
    raw: list[RawTurn] = []
    blocks: list[list[str]] = []
    current_block: list[str] = []
    for line in lines:
        if line.strip():
            current_block.append(line.strip())
        else:
            if current_block:
                blocks.append(current_block)
                current_block = []
    if current_block:
        blocks.append(current_block)

    for block in blocks:
        if len(block) >= 2:
            speaker = _clean_speaker(block[0])
            text = " ".join(block[1:])
            # Heuristic: first line should look like a name (no colon, < 50 chars, not a header)
            if len(speaker) < 50 and ":" not in speaker and not _HEADER_LINE_RE.match(block[0] + ":"):
                raw.append((speaker, text, None))
    if len(raw) < 2:
        return []
    raw = _normalize_speaker_map(raw)
    raw = _merge_consecutive(raw)
    return _to_turn_objects(raw)


_FMT_E_TS_RE = re.compile(r"\((\d{1,2}:\d{2}(?::\d{2})?)\)")


def _parse_txt_format_e(lines: list[str]) -> list[Turn]:
    """'Speaker (HH:MM):\ntext' blocks."""
    raw: list[RawTurn] = []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        m = _FMT_E_RE.match(line)
        if m and not _HEADER_LINE_RE.match(line):
            speaker = _clean_speaker(m.group(1))
            ts: Optional[float] = None
            ts_m = _FMT_E_TS_RE.search(line)
            if ts_m:
                try:
                    ts = _parse_timecode(ts_m.group(1))
                except (ValueError, IndexError):
                    pass
            i += 1
            text_lines = []
            while i < len(lines) and lines[i].strip() and not _FMT_E_RE.match(lines[i]):
                text_lines.append(lines[i].strip())
                i += 1
            if text_lines:
                raw.append((speaker, " ".join(text_lines), ts))
        else:
            i += 1
    raw = _normalize_speaker_map(raw)
    raw = _merge_consecutive(raw)
    return _to_turn_objects(raw)


# ── Markdown Parser ──────────────────────────────────────────────────────────

_MD_HEADING_RE = re.compile(r"^#{1,6}\s+")
_MD_HR_RE = re.compile(r"^(-{3,}|\*{3,}|_{3,})\s*$")
_MD_BOLD_SPEAKER_TS_RE = re.compile(
    r"^\*\*([^*]+)\*\*\s+(\d{1,2}:\d{2}(?::\d{2})?)\s*(.*)"
)
_MD_BOLD_SPEAKER_RE = re.compile(r"^\*\*([^*]+)\*\*\s*(.*)")
_MD_BOLD_RE = re.compile(r"\*\*([^*]+)\*\*")
_MD_ITALIC_RE = re.compile(r"\*([^*]+)\*")
_MD_BULLET_RE = re.compile(r"^[-*+]\s+")


def _strip_markdown(text: str) -> str:
    """Strip markdown formatting, converting bold speakers to Format B style."""
    out_lines: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        # Skip headings and horizontal rules
        if _MD_HEADING_RE.match(stripped) or _MD_HR_RE.match(stripped):
            continue
        # Convert **Speaker** HH:MM [optional inline text] to Format B
        m = _MD_BOLD_SPEAKER_TS_RE.match(stripped)
        if m:
            speaker = m.group(1).strip()
            ts = m.group(2)
            inline_text = m.group(3).strip()
            out_lines.append(f"{speaker}  {ts}")
            if inline_text:
                # Strip remaining bold/italic from inline text
                inline_text = _MD_BOLD_RE.sub(r"\1", inline_text)
                inline_text = _MD_ITALIC_RE.sub(r"\1", inline_text)
                out_lines.append(inline_text)
            continue
        # Convert **Speaker** (no timestamp) to speaker line for Format D
        m = _MD_BOLD_SPEAKER_RE.match(stripped)
        if m and not m.group(2).strip():
            out_lines.append(m.group(1).strip())
            continue
        # Strip bullet prefixes
        stripped = _MD_BULLET_RE.sub("", stripped)
        # Strip remaining bold/italic markers
        stripped = _MD_BOLD_RE.sub(r"\1", stripped)
        stripped = _MD_ITALIC_RE.sub(r"\1", stripped)
        out_lines.append(stripped)
    return "\n".join(out_lines)


def _parse_markdown(text: str) -> list[Turn]:
    """Parse markdown transcript by stripping formatting and delegating to TXT."""
    cleaned = _strip_markdown(text)
    return _parse_txt(cleaned)


# ── CSV Parser ───────────────────────────────────────────────────────────────

_CSV_SPEAKER_NAMES = {"speaker", "speaker_name", "name", "participant"}
_CSV_TEXT_NAMES = {"text", "content", "transcript", "utterance", "body"}
_CSV_TIME_NAMES = {"start", "start_time", "timestamp", "time"}


def _parse_csv(text: str) -> list[Turn]:
    """Parse CSV transcript with auto-detected or positional columns."""
    reader = csv.reader(io.StringIO(text))
    rows = list(reader)
    if not rows:
        return []

    # Try to detect header row
    header = [h.strip().lower() for h in rows[0]]
    speaker_col: Optional[int] = None
    text_col: Optional[int] = None
    time_col: Optional[int] = None

    for i, h in enumerate(header):
        if h in _CSV_SPEAKER_NAMES and speaker_col is None:
            speaker_col = i
        elif h in _CSV_TEXT_NAMES and text_col is None:
            text_col = i
        elif h in _CSV_TIME_NAMES and time_col is None:
            time_col = i

    data_start = 0
    if speaker_col is not None or text_col is not None:
        # Header detected
        data_start = 1
    else:
        # Positional fallback: col0=speaker, col1=text, col2=timestamp
        if len(header) >= 2:
            speaker_col = 0
            text_col = 1
            if len(header) >= 3:
                time_col = 2

    if text_col is None:
        return []

    raw: list[RawTurn] = []
    for row in rows[data_start:]:
        if len(row) <= max(c for c in (speaker_col, text_col, time_col) if c is not None):
            continue
        speaker = row[speaker_col].strip() if speaker_col is not None else "Unknown"
        text = row[text_col].strip() if text_col is not None else ""
        ts: Optional[float] = None
        if time_col is not None and time_col < len(row) and row[time_col].strip():
            try:
                ts = _parse_timecode(row[time_col].strip())
            except (ValueError, IndexError):
                # Try as float seconds
                try:
                    ts = float(row[time_col].strip())
                except ValueError:
                    pass
        if not text:
            continue
        if not speaker:
            speaker = "Unknown"
        raw.append((speaker, text, ts))

    raw = _normalize_speaker_map(raw)
    raw = _merge_consecutive(raw)
    return _to_turn_objects(raw)


# ── JSON Parser ──────────────────────────────────────────────────────────────

_JSON_SEGMENT_KEYS = {"segments", "results", "utterances", "transcript", "items"}
_JSON_SPEAKER_KEYS = {"speaker", "speaker_name", "speaker_label", "name", "participant", "channel"}
_JSON_TEXT_KEYS = {"text", "content", "transcript", "utterance", "body", "punctuated_word"}
_JSON_TIME_KEYS = {"start", "start_time", "timestamp", "time", "start_ts"}
_JSON_WORDS_KEYS = {"words", "tokens"}


def _find_segments(data: object, depth: int = 0) -> Optional[list[dict]]:
    """Search for an array of segment dicts up to 2 levels deep."""
    if depth > 2:
        return None
    if isinstance(data, list) and data and isinstance(data[0], dict):
        return data
    if isinstance(data, dict):
        # Check known keys first
        for key in _JSON_SEGMENT_KEYS:
            if key in data:
                val = data[key]
                if isinstance(val, list) and val and isinstance(val[0], dict):
                    return val
        # Search all values
        for val in data.values():
            result = _find_segments(val, depth + 1)
            if result:
                return result
    return None


def _extract_text_from_segment(seg: dict) -> str:
    """Extract text from a segment, handling words arrays."""
    # Direct text field
    for key in _JSON_TEXT_KEYS:
        if key in seg and isinstance(seg[key], str) and seg[key].strip():
            return seg[key].strip()
    # Words array
    for key in _JSON_WORDS_KEYS:
        if key in seg and isinstance(seg[key], list):
            words = seg[key]
            parts = []
            for w in words:
                if isinstance(w, dict):
                    for tk in ("word", "text", "punctuated_word", "value"):
                        if tk in w and isinstance(w[tk], str):
                            parts.append(w[tk])
                            break
                elif isinstance(w, str):
                    parts.append(w)
            if parts:
                return " ".join(parts)
    return ""


def _extract_speaker_from_segment(seg: dict) -> str:
    """Extract speaker label from a segment dict."""
    for key in _JSON_SPEAKER_KEYS:
        if key in seg and seg[key] is not None:
            return str(seg[key]).strip()
    return "Unknown"


def _extract_time_from_segment(seg: dict) -> Optional[float]:
    """Extract start time from a segment dict."""
    for key in _JSON_TIME_KEYS:
        if key in seg and seg[key] is not None:
            val = seg[key]
            if isinstance(val, (int, float)):
                return float(val)
            if isinstance(val, str):
                try:
                    return _parse_timecode(val)
                except (ValueError, IndexError):
                    try:
                        return float(val)
                    except ValueError:
                        pass
    return None


def _parse_json(text: str) -> list[Turn]:
    """Parse JSON transcript with auto-detected segment structure."""
    try:
        data = json_mod.loads(text)
    except (json_mod.JSONDecodeError, ValueError):
        return []

    segments = _find_segments(data)
    if not segments:
        return []

    raw: list[RawTurn] = []
    for seg in segments:
        if not isinstance(seg, dict):
            continue
        text_content = _extract_text_from_segment(seg)
        if not text_content:
            continue
        speaker = _extract_speaker_from_segment(seg)
        ts = _extract_time_from_segment(seg)
        raw.append((speaker, text_content, ts))

    raw = _normalize_speaker_map(raw)
    raw = _merge_consecutive(raw)
    return _to_turn_objects(raw)


# ── DOCX / PDF extraction ─────────────────────────────────────────────────────

def _extract_docx_text(data: bytes) -> str:
    import docx  # python-docx
    doc = docx.Document(io.BytesIO(data))
    return "\n".join(p.text for p in doc.paragraphs)


def _extract_pdf_text(data: bytes) -> str:
    try:
        import fitz  # PyMuPDF
        with fitz.open(stream=data, filetype="pdf") as pdf_doc:
            return "\n".join(page.get_text() for page in pdf_doc)
    except ImportError:
        pass
    import pdfplumber
    with pdfplumber.open(io.BytesIO(data)) as pdf:
        return "\n".join(p.extract_text() or "" for p in pdf.pages)


# ── Public API ────────────────────────────────────────────────────────────────

def parse_transcript(
    data: bytes,
    filename: str,
    source_id: str,
) -> ParsedTranscript:
    """
    Parse a transcript file.

    Args:
        data: Raw file bytes.
        filename: Original filename (used to detect format).
        source_id: Meeting ID or baseline-pack ID (e.g. M-000042).

    Returns:
        ParsedTranscript

    Raises:
        TranscriptParseError: On unsupported format or too-small input.
    """
    if len(data) < TRANSCRIPT_MIN_CHARS:
        raise TranscriptParseError(f"Upload too small ({len(data)} bytes).")

    suffix = Path(filename).suffix.lower()

    # Normalize to text where possible
    raw_text: Optional[str] = None
    detected_format: str

    if suffix == ".docx":
        raw_text = _extract_docx_text(data)
        detected_format = "docx"
    elif suffix == ".pdf":
        raw_text = _extract_pdf_text(data)
        detected_format = "pdf"
    else:
        try:
            raw_text = data.decode("utf-8")
        except UnicodeDecodeError:
            raw_text = data.decode("latin-1", errors="replace")
        detected_format = suffix.lstrip(".")

    raw_text = _normalize_text(raw_text or "")
    # Strip boilerplate lines globally
    raw_text = "\n".join(
        line for line in raw_text.splitlines() if not _BOILERPLATE_RE.search(line)
    )

    if len(raw_text.strip()) < TRANSCRIPT_MIN_CHARS:
        raise TranscriptParseError("Transcript text too short after extraction.")

    # ── Format detection ──
    first_non_blank = next((l.strip() for l in raw_text.splitlines() if l.strip()), "")

    if suffix == ".vtt" or first_non_blank.upper() == "WEBVTT":
        turns = _parse_vtt(raw_text)
        detected_format = "vtt"
    elif suffix == ".srt" or (
        _SRT_INDEX_RE.match(first_non_blank) and _TIMECODE_RE.search(raw_text)
    ):
        turns = _parse_srt(raw_text)
        detected_format = "srt"
    elif suffix == ".json" or first_non_blank[:1] in ("{", "["):
        turns = _parse_json(raw_text)
        detected_format = "json"
    elif suffix == ".csv":
        turns = _parse_csv(raw_text)
        detected_format = "csv"
    elif suffix in (".md", ".markdown"):
        turns = _parse_markdown(raw_text)
        detected_format = "md"
    elif detected_format in ("docx", "pdf"):
        turns = _parse_txt(raw_text)
    else:
        turns = _parse_txt(raw_text)
        detected_format = "txt"

    if not turns:
        turns = [Turn(turn_id=1, speaker_label="Unknown", text=raw_text.strip()[:5000], start_time_sec=None)]

    # ── Word count / truncation ──
    wc = _word_count(turns)
    truncated = False
    if wc > TRANSCRIPT_MAX_WORDS:
        logger.warning(
            "Transcript %s has %d words; truncating to %d.", source_id, wc, TRANSCRIPT_MAX_WORDS
        )
        turns = _truncate_at_word_boundary(turns, TRANSCRIPT_MAX_WORDS)
        wc = _word_count(turns)
        truncated = True
        # Renumber turn_ids after truncation
        turns = [Turn(turn_id=i + 1, **t.model_dump(exclude={"turn_id"})) for i, t in enumerate(turns)]

    speaker_labels = _dedupe_speakers([t.speaker_label for t in turns])

    return ParsedTranscript(
        source_id=source_id,
        turns=turns,
        speaker_labels=speaker_labels,
        metadata=TranscriptMetadata(
            original_format=detected_format,
            turn_count=len(turns),
            word_count=wc,
            truncated=truncated,
        ),
    )
